apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - image: nginx
          name: server

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: app
  type: NodePort
